# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4232abb1cfb55f9dcad72650e968bccdaa3b527a50901e6f428edc83db23e22e343e6c6f21b46f529649cb0437c2fc8d772409576fe131f43cd172546fa0324

test:
  secret_key_base: 1c1cfebe575aeb0caf6ab91b4b7d8aa59e517585244d8faf635004850b302b776e1dcad7d09a5ba41e457b5e7fd36ecf3f5aac17baa2fc43c236b024df3c240e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
